### ISSUE TITLE
Cant build on Arch 1.0.3

### ISSUE THREAD

**Issue by gavr123456789** [philippejer/vala-language-server-alpha#9]
Again)  
I understand that this is most likely due to the fact that you use your version of Valac. Are you going to do PR. Recently, a similar [story](https://github.com/frida/vala/issues/2#issuecomment-546564409) happened with the fork valac from Frida.  

Error:
```
...
../src/Server.vala:901.61-901.85: **error**: The name `get_suppr_errors' does not exist in the context of `Vls.Reporter'
      if (reporter == null || reporter.get_errors()  > 0 || reporter.get_suppr_errors() > 0)
                                                            ^^^^^^^^^^^^^^^^^^^^^^^^^
Compilation failed: 1 error(s), 0 warning(s)
[2/40] Compiling Vala source ../src/pr...alization.vala ../tests/TestMain.vala.
FAILED: vala-language-server-tests@exe/src/Server.c vala-language-server-tests@exe/src/Reporter.c vala-language-server-tests@exe/src/Context.c vala-language-server-tests@exe/src/visitors/FindNode.c vala-language-server-tests@exe/src/visitors/FindNodeInFile.c vala-language-server-tests@exe/src/visitors/FindNodeByPosition.c vala-language-server-tests@exe/src/visitors/FindSymbolByPosition.c vala-language-server-tests@exe/src/visitors/FindSymbolByName.c vala-language-server-tests@exe/src/visitors/FindSymbolReferences.c vala-language-server-tests@exe/src/visitors/FindSymbolsInFile.c vala-language-server-tests@exe/src/helpers/CodeHelpers.c vala-language-server-tests@exe/src/helpers/CompletionHelpers.c vala-language-server-tests@exe/src/helpers/DocumentSymbolHelpers.c vala-language-server-tests@exe/src/helpers/MiscHelpers.c vala-language-server-tests@exe/src/helpers/TestHelpers.c vala-language-server-tests@exe/src/protocol/Protocol.c vala-language-server-tests@exe/src/protocol/JsonSerialization.c vala-language-server-tests@exe/tests/TestMain.c 
valac -C --enable-gobject-tracing --pkg=posix --pkg gio-unix-2.0 --pkg libvala-0.46 --pkg jsonrpc-glib-1.0 --pkg gio-2.0 --pkg gee-0.8 --pkg gobject-2.0 --target-glib 2.54 --pkg glib-2.0 --color=always --directory vala-language-server-tests@exe --basedir ../ ../src/protocol/JsonSerializable.vapi ../src/Server.vala ../src/Reporter.vala ../src/Context.vala ../src/visitors/FindNode.vala ../src/visitors/FindNodeInFile.vala ../src/visitors/FindNodeByPosition.vala ../src/visitors/FindSymbolByPosition.vala ../src/visitors/FindSymbolByName.vala ../src/visitors/FindSymbolReferences.vala ../src/visitors/FindSymbolsInFile.vala ../src/helpers/CodeHelpers.vala ../src/helpers/CompletionHelpers.vala ../src/helpers/DocumentSymbolHelpers.vala ../src/helpers/MiscHelpers.vala ../src/helpers/TestHelpers.vala ../src/protocol/Protocol.vala ../src/protocol/JsonSerialization.vala ../tests/TestMain.vala
../src/Server.vala:901.61-901.85: **error**: The name `get_suppr_errors' does not exist in the context of `Vls.Reporter'
      if (reporter == null || reporter.get_errors()  > 0 || reporter.get_suppr_errors() > 0)
                                                            ^^^^^^^^^^^^^^^^^^^^^^^^^
Compilation failed: 1 error(s), 0 warning(s)
ninja: build stopped: subcommand failed.
```

**Comment by Fuhrmann** [comment]
Same problem here when I try to build. Using Xubuntu 19.10. Here are some details:

```
fuhrmann in vala-language-server-alpha on master 
➜ meson build --buildtype=release
The Meson build system
Version: 0.52.0
Source dir: /home/fuhrmann/apps/vala-language-server-alpha
Build dir: /home/fuhrmann/apps/vala-language-server-alpha/build
Build type: native build
Project name: vala-language-server
Project version: undefined
C compiler for the host machine: cc (gcc 9.2.1 "cc (Ubuntu 9.2.1-9ubuntu2) 9.2.1 20191008")
C linker for the host machine: GNU ld.bfd 2.33
Vala compiler for the host machine: valac (valac 0.46.0)
Host machine cpu family: x86_64
Host machine cpu: x86_64
Found pkg-config: /usr/bin/pkg-config (0.29.1)
Run-time dependency glib-2.0 found: YES 2.62.1
Run-time dependency gobject-2.0 found: YES 2.62.1
Run-time dependency gee-0.8 found: YES 0.20.2
Run-time dependency gio-2.0 found: YES 2.62.1
Run-time dependency jsonrpc-glib-1.0 found: YES 3.33.3
Run-time dependency libvala-0.46 found: YES 0.46.0
Run-time dependency gio-unix-2.0 found: YES 2.62.1
Message: vala_version: Vala 0.46.0
Build targets in project: 2
Found ninja-1.9.0 at /usr/bin/ninja
```

**Comment by gavr123456789** [comment]
@Fuhrmann U can build it with [that](https://gitlab.gnome.org/philippejer/vala/tree/0.46.3-exp) (Also 1.0.2 works with usual `valac`)  
But i have problems with build 0.46.3-exp too. 
```
valaversion.vala:28.35-28.35: error: syntax error, expected identifier
    public const int MAJOR_VERSION = ;
                                     ^
valaversion.vala:33.35-33.35: error: syntax error, expected identifier
    public const int MINOR_VERSION = ;
                                     ^
valaversion.vala:38.35-38.35: error: syntax error, expected identifier
    public const int MICRO_VERSION = ;
                                     ^
Compilation failed: 3 error(s), 0 warning(s)
make[2]: *** [Makefile:1586: vala.vala.stamp] Ошибка 1
make[2]: выход из каталога «/home/gavr/dev/Builds/vala-0.46.3-exp/vala»
make[1]: *** [Makefile:543: all-recursive] Ошибка 1
make[1]: выход из каталога «/home/gavr/dev/Builds/vala-0.46.3-exp»
make: *** [Makefile:431: all] Ошибка 2
```

Had an idea to build VLS 1.0.3 with custom compiler and then create a AppImage of it.

**Comment by philippejer** [comment]
Hello, thanks for the feedback and sorry for the late answer...

@Fuhrmann Really sorry, I had actually fixed the dependency on the "-exp" branch reported by @gavr123456789 but reintroduced another one recently (https://github.com/philippejer/vala-language-server-alpha/commit/20e4a55b9f1eb919cba9ae60b12f440055775f07)...

This is fixed now (https://github.com/philippejer/vala-language-server-alpha/commit/f42aede9cafefb10f71dbbc5a22ab9399d3502a8), the server builds with the regular compiler (46.0 should be good, although I've personally switched to 46.3 which works well)...

I'll be more careful and do some sanity checks with the vanilla compiler next time...

**Comment by philippejer** [comment]
@gavr123456789 I think I have had the same issue the first time I tried to compile Vala, it might not be particularly related to my branch (unless it's something else)...

The Vala build from (non-precompiled) sources uses git to determine the latest tag and generate the `MAJOR_VERSION` constants and so on. So you need to have Git on your PATH and to make sure to fetch the tags (`git fetch --tags`). The "magic" happens [here](https://gitlab.gnome.org/philippejer/vala/blob/0.46.3-exp/build-aux/git-version-gen).

Could you check the output of `git describe --abbrev=4 HEAD`? (in the shell where you compile Vala)

On my side I get `0.46.3-9-g44ca`...

In case that helps, I have just recompiled my branch from the latest commit under MinGW-w64 like so:

```shell
git reset --hard 44ca2ac87
git clean -fdx
./autogen.sh --disable-valadoc
make && make install
```

Here is what my `valaversion.vala` looks like now:

![image](https://user-images.githubusercontent.com/10595772/68123823-42643800-ff0e-11e9-8f90-862c9aa57a0f.png)

Note that under MinGW there is a bug in the install step and one of the libraries is copied at the wrong location, so I run this little script after `make install`:

```shell
# Install workaround: libtool does not copy this DLL at the right place under MinGW-64
# (search "place dlname in correct position for cygwin" in ltmain.sh)
mv /mingw64/lib/bin/libvalaccodegen.dll /mingw64/bin/
rmdir /mingw64/lib/bin
```
